/* CapitalBridge — shared JS */
(function () {
  window.CB_GRANTS = [
    {
      id: "sme-growth-2026",
      name: "SME Growth Capital Grant",
      category: "SME",
      country: "United States",
      industry: "General Business",
      shortDescription: "Working capital for small and mid-sized businesses expanding operations, hiring, or upgrading equipment.",
      fullDescription: "The SME Growth Capital Grant supports established small and mid-sized businesses pursuing measurable expansion. Funds may be used for hiring, equipment, lease build-outs, software systems, and operating capital tied to a documented growth plan.",
      fundingMin: 15000, fundingMax: 150000, processingFee: 85, processingTime: "5–10 business days",
      eligibility: ["Registered business operating for 12+ months","Annual revenue between $50,000 and $5,000,000","Demonstrable growth or expansion plan","Owner is 18+ and a legal resident of the operating country"],
      documents: ["Government-issued ID","Business registration certificate","Most recent profit & loss statement","Brief growth or use-of-funds plan"],
      benefits: ["Non-dilutive funding (no equity given up)","Documentation assistance throughout review","Priority routing to matched funders"]
    },
    {
      id: "startup-launchpad", name: "Startup Launchpad Grant", category: "Startup", country: "Global", industry: "Technology & Innovation",
      shortDescription: "Pre-seed capital for early-stage founders building a product, validating a market, or assembling a founding team.",
      fullDescription: "Startup Launchpad backs founders in the first 24 months of building. The grant prioritizes clear problem framing, a working prototype or detailed roadmap, and a credible plan to reach first revenue.",
      fundingMin: 5000, fundingMax: 75000, processingFee: 65, processingTime: "7–14 business days",
      eligibility: ["Company incorporated within the last 24 months","At least one full-time founder","Has an MVP, prototype, or detailed product roadmap","Operating in technology, software, or innovation-led services"],
      documents: ["Founder ID","Incorporation document","Pitch deck or one-page summary","Product or roadmap link (optional)"],
      benefits: ["Early-stage friendly review (no revenue required)","Founder advisory introductions","Access to alumni funder network"]
    },
    {
      id: "agri-yield-program", name: "Agricultural Yield Program", category: "Agriculture", country: "Global", industry: "Agriculture & Food",
      shortDescription: "Funding for farm operators and agribusinesses investing in yield, irrigation, storage, or processing capacity.",
      fullDescription: "The Agricultural Yield Program supports operators improving productivity through irrigation, soil amendment, mechanization, cold storage, or processing infrastructure. Co-operatives are eligible to apply on behalf of grouped farms.",
      fundingMin: 10000, fundingMax: 200000, processingFee: 95, processingTime: "10–15 business days",
      eligibility: ["Active farm or agribusiness with verifiable land use or lease","Investment plan tied to yield, storage, or processing","Owner or co-operative officer authorized to receive funds"],
      documents: ["Government-issued ID","Land ownership or lease documentation","Investment plan or supplier quote"],
      benefits: ["Equipment-focused funding tracks","Co-operative group applications accepted","Technical review by agronomy partners"]
    },
    {
      id: "tech-innovation-grant", name: "Tech Innovation Grant", category: "Tech", country: "United States", industry: "Software & Deep Tech",
      shortDescription: "Targeted funding for software, AI, and deep-tech ventures with defensible technology and a clear go-to-market.",
      fullDescription: "Tech Innovation Grant funds R&D-heavy ventures across applied AI, developer tools, cybersecurity, and adjacent deep-tech categories. Reviewers prioritize technical defensibility, team credibility, and a credible commercialization plan.",
      fundingMin: 25000, fundingMax: 250000, processingFee: 125, processingTime: "10–15 business days",
      eligibility: ["Operating technology company","Working product, prototype, or research output","Team with relevant technical background"],
      documents: ["Founder ID","Incorporation document","Technical brief (1–2 pages)","Commercial plan or pipeline summary"],
      benefits: ["Largest funding bands of any program","Technical reviewer feedback","Eligible for follow-on capital introductions"]
    },
    {
      id: "women-owned-business", name: "Women-Owned Business Grant", category: "Diversity", country: "Global", industry: "All Industries",
      shortDescription: "Dedicated capital for businesses majority-owned and operated by women across any qualifying industry.",
      fullDescription: "This grant supports women-led ventures expanding revenue, headcount, or market reach. Ownership of 51%+ by one or more women is required. Documentation support is provided throughout the review.",
      fundingMin: 10000, fundingMax: 100000, processingFee: 75, processingTime: "5–10 business days",
      eligibility: ["51%+ ownership by one or more women","Registered business in operation","Owner is 18+ and a legal resident of the operating country"],
      documents: ["Owner ID","Business registration document","Brief use-of-funds plan"],
      benefits: ["Dedicated reviewer pool","Mentor network access","Priority documentation support"]
    },
    {
      id: "green-energy-fund", name: "Green Energy Transition Fund", category: "Sustainability", country: "Global", industry: "Energy & Sustainability",
      shortDescription: "Capital for businesses investing in solar, efficiency upgrades, EV fleets, or sustainable supply chain shifts.",
      fullDescription: "Green Energy Transition Fund supports operating businesses making verifiable sustainability investments — solar installs, fleet electrification, efficiency retrofits, and certified sustainable sourcing transitions.",
      fundingMin: 20000, fundingMax: 180000, processingFee: 110, processingTime: "10–15 business days",
      eligibility: ["Operating business with a sustainability investment plan","Quotes or supplier estimates for proposed investment"],
      documents: ["Business registration","Supplier quote or project plan","Most recent utility or fleet baseline (if available)"],
      benefits: ["Specialized sustainability reviewers","Eligible for stacked utility incentives","Documentation help for measurement & verification"]
    },
    { id: "minority-owned-capital", name: "Minority-Owned Business Capital Grant", category: "Diversity", country: "United States", industry: "All Industries",
      shortDescription: "Targeted growth capital for businesses majority-owned by minority entrepreneurs across qualifying industries.",
      fullDescription: "This program funds minority-owned ventures expanding capacity, hiring, or entering new markets. Documentation support and a dedicated reviewer pool shorten the review cycle.",
      fundingMin: 10000, fundingMax: 120000, processingFee: 80, processingTime: "5–10 business days",
      eligibility: ["51%+ ownership by minority founder(s)","Registered business in operation","Owner is 18+ and legally resident"],
      documents: ["Owner ID","Business registration","Brief use-of-funds plan"],
      benefits: ["Dedicated reviewer pool","Mentor network access","Documentation support"] },
    { id: "veteran-business-fund", name: "Veteran-Owned Business Fund", category: "Diversity", country: "United States", industry: "All Industries",
      shortDescription: "Capital for veteran-owned and service-disabled veteran-owned businesses scaling operations.",
      fullDescription: "The Veteran-Owned Business Fund supports U.S. veterans operating businesses with active revenue or contracts. SDVOSB-certified businesses receive priority review.",
      fundingMin: 15000, fundingMax: 140000, processingFee: 90, processingTime: "7–14 business days",
      eligibility: ["51%+ veteran ownership","DD-214 or VA verification","Operating business with revenue or contracts"],
      documents: ["Veteran verification (DD-214)","Business registration","Most recent P&L"],
      benefits: ["Priority routing for SDVOSB","Government contracting referrals","Documentation help"] },
    { id: "rural-development", name: "Rural Development Grant", category: "Community", country: "United States", industry: "Rural & Community",
      shortDescription: "Funding for businesses operating in rural communities — agriculture, light manufacturing, healthcare, and retail.",
      fullDescription: "Supports operating businesses headquartered in rural-designated counties. Funds may be used for equipment, hiring, facilities, and community-serving expansion.",
      fundingMin: 10000, fundingMax: 175000, processingFee: 95, processingTime: "10–15 business days",
      eligibility: ["Business operating in a rural-designated county","Documented community benefit"],
      documents: ["Business registration","Proof of operating address","Use-of-funds plan"],
      benefits: ["Stackable with USDA programs","Community-impact reviewers","Equipment financing tracks"] },
    { id: "manufacturing-modernization", name: "Manufacturing Modernization Grant", category: "Manufacturing", country: "United States", industry: "Manufacturing",
      shortDescription: "Capital to upgrade equipment, automate lines, or expand domestic manufacturing capacity.",
      fullDescription: "Funds CNC upgrades, robotics, automation software, and capacity expansion for small and mid-sized U.S. manufacturers. Reshoring projects receive priority.",
      fundingMin: 25000, fundingMax: 300000, processingFee: 140, processingTime: "12–18 business days",
      eligibility: ["U.S.-based manufacturer","Documented equipment or automation plan","Operating 24+ months"],
      documents: ["Business registration","Equipment quotes","Production capacity baseline"],
      benefits: ["Reshoring priority","Capital equipment specialists","Largest funding bands"] },
    { id: "healthcare-innovation", name: "Healthcare Innovation Grant", category: "Healthcare", country: "United States", industry: "Healthcare & Life Sciences",
      shortDescription: "Funding for clinics, digital health, medical devices, and healthcare service expansion.",
      fullDescription: "Backs healthcare providers and digital-health ventures investing in patient access, clinical software, or device development. Compliance documentation is reviewed.",
      fundingMin: 20000, fundingMax: 250000, processingFee: 130, processingTime: "10–15 business days",
      eligibility: ["Operating healthcare business or certified provider","Compliance documentation in place"],
      documents: ["Business registration","Provider license or device classification","Use-of-funds plan"],
      benefits: ["Compliance-aware reviewers","Device & digital-health tracks","Follow-on funder introductions"] },
    { id: "education-program-grant", name: "Education Program Grant", category: "Education", country: "Global", industry: "Education & Training",
      shortDescription: "Funding for schools, training providers, and edtech building accessible learning programs.",
      fullDescription: "Supports licensed schools, training centers, and edtech ventures expanding curriculum, learner access, or instructor capacity.",
      fundingMin: 8000, fundingMax: 90000, processingFee: 70, processingTime: "7–14 business days",
      eligibility: ["Licensed school, training provider, or edtech company","Defined learner outcomes"],
      documents: ["Registration / license","Program outline","Use-of-funds plan"],
      benefits: ["Edtech-friendly review","Curriculum advisor access","Documentation support"] },
    { id: "creative-arts-grant", name: "Creative Arts & Media Grant", category: "Creative", country: "Global", industry: "Arts & Media",
      shortDescription: "Project funding for creative studios, independent media, film, music, and design houses.",
      fullDescription: "Funds production, post-production, distribution, and studio capacity for independent creative businesses with a documented project pipeline.",
      fundingMin: 5000, fundingMax: 80000, processingFee: 60, processingTime: "7–14 business days",
      eligibility: ["Registered creative business or studio","Active project or pipeline"],
      documents: ["Business registration","Project brief","Portfolio or samples"],
      benefits: ["Project-based review","Distribution introductions","Documentation help"] },
    { id: "ecommerce-scale-grant", name: "E-Commerce Scale Grant", category: "Retail", country: "Global", industry: "Retail & E-Commerce",
      shortDescription: "Working capital for online sellers scaling inventory, fulfillment, or paid acquisition.",
      fullDescription: "Backs Shopify, Amazon, and DTC sellers with documented revenue scaling fulfillment, inventory buys, or acquisition spend tied to a unit-economics plan.",
      fundingMin: 10000, fundingMax: 120000, processingFee: 85, processingTime: "5–10 business days",
      eligibility: ["Operating online store with 6+ months of sales","Documented unit economics"],
      documents: ["Business registration","Store revenue report (last 90 days)","Use-of-funds plan"],
      benefits: ["Inventory-aware reviewers","Acquisition spend tracks","Fast turnaround"] },
    { id: "restaurant-hospitality", name: "Restaurant & Hospitality Grant", category: "Hospitality", country: "United States", industry: "Restaurants & Hospitality",
      shortDescription: "Capital for restaurants, cafés, food trucks, and small hotels expanding or recovering capacity.",
      fullDescription: "Funds equipment, build-out, seasonal hiring, and working capital for operating food-service and small hospitality businesses.",
      fundingMin: 8000, fundingMax: 100000, processingFee: 75, processingTime: "5–10 business days",
      eligibility: ["Operating restaurant, café, or hospitality business","Active food-service or lodging license"],
      documents: ["Business license","Most recent sales summary","Use-of-funds plan"],
      benefits: ["Seasonal cycle aware","Equipment tracks","Documentation help"] },
    { id: "construction-trades", name: "Construction & Trades Grant", category: "Trades", country: "United States", industry: "Construction & Trades",
      shortDescription: "Funding for licensed contractors and trades businesses investing in crew, tools, or fleet.",
      fullDescription: "Backs licensed general contractors, electricians, plumbers, HVAC, and specialty trades scaling crews, tools, or service-area expansion.",
      fundingMin: 10000, fundingMax: 130000, processingFee: 90, processingTime: "7–14 business days",
      eligibility: ["Licensed contractor or trades business","Active jobs or signed contracts","Insurance in good standing"],
      documents: ["Contractor license","Insurance certificate","Pipeline summary"],
      benefits: ["Trades-aware reviewers","Equipment financing tracks","Insurance documentation help"] },
    { id: "transportation-logistics", name: "Transportation & Logistics Grant", category: "Logistics", country: "United States", industry: "Transportation & Logistics",
      shortDescription: "Funding for trucking, last-mile delivery, and small logistics operators investing in fleet or routes.",
      fullDescription: "Supports DOT-registered carriers and last-mile delivery operators expanding fleet, adding routes, or upgrading telematics.",
      fundingMin: 15000, fundingMax: 200000, processingFee: 110, processingTime: "10–15 business days",
      eligibility: ["DOT-registered carrier or licensed delivery operator","Active contracts or routes","Insurance in good standing"],
      documents: ["DOT registration / license","Insurance certificate","Fleet inventory or route plan"],
      benefits: ["Fleet-aware reviewers","Telematics upgrade tracks","Equipment financing introductions"] },
    { id: "nonprofit-capacity", name: "Nonprofit Capacity Grant", category: "Nonprofit", country: "Global", industry: "Nonprofit & Social Impact",
      shortDescription: "Unrestricted capacity funding for 501(c)(3) and equivalent nonprofits scaling programs or staff.",
      fullDescription: "Supports nonprofits with documented programs scaling staff, operations, or measurement capacity. Audited financials accelerate review.",
      fundingMin: 10000, fundingMax: 150000, processingFee: 75, processingTime: "10–15 business days",
      eligibility: ["Registered nonprofit (501(c)(3) or equivalent)","Documented program activity","Board governance in place"],
      documents: ["Nonprofit determination letter","Most recent financials","Program impact summary"],
      benefits: ["Capacity-focused reviewers","Funder-network introductions","Documentation help"] },
    { id: "export-trade-grant", name: "Export & Trade Expansion Grant", category: "Trade", country: "United States", industry: "Import / Export",
      shortDescription: "Funding for U.S. businesses expanding into international markets — trade shows, certifications, distribution.",
      fullDescription: "Backs U.S. operators investing in international expansion — trade show presence, foreign certifications, distributor onboarding, or export compliance.",
      fundingMin: 12000, fundingMax: 160000, processingFee: 105, processingTime: "10–15 business days",
      eligibility: ["U.S.-registered business with export plan","Product or service ready for international sale"],
      documents: ["Business registration","Export plan or trade-show roster","Product or service brief"],
      benefits: ["Export-aware reviewers","Trade compliance support","Distributor introductions"] },
    { id: "fintech-innovation", name: "Fintech Innovation Grant", category: "Tech", country: "Global", industry: "Financial Technology",
      shortDescription: "Capital for licensed fintech operators building payments, lending, or wealth infrastructure.",
      fullDescription: "Backs fintech ventures with licensing in place or in progress — payments, lending, wealth, or B2B financial infrastructure. Compliance documentation is reviewed.",
      fundingMin: 25000, fundingMax: 220000, processingFee: 135, processingTime: "12–18 business days",
      eligibility: ["Operating fintech with active or pending licensing","Compliance program in place"],
      documents: ["Incorporation document","Licensing status","Product brief & compliance summary"],
      benefits: ["Compliance-aware reviewers","Licensing introductions","Follow-on capital network"] },
    { id: "biotech-research", name: "Biotech & Research Grant", category: "Research", country: "United States", industry: "Biotech & Research",
      shortDescription: "R&D funding for early-stage biotech, diagnostics, and research-driven life sciences ventures.",
      fullDescription: "Funds preclinical R&D, instrumentation, and translational research for biotech and diagnostics startups. IP position and team credentials are reviewed.",
      fundingMin: 30000, fundingMax: 300000, processingFee: 150, processingTime: "14–21 business days",
      eligibility: ["Operating biotech or research company","Research plan with milestones","Team with relevant credentials"],
      documents: ["Incorporation document","Research plan","Team bios / IP summary"],
      benefits: ["Scientific reviewer pool","Largest funding bands","Follow-on capital network"] },
    { id: "cybersecurity-grant", name: "Cybersecurity Resilience Grant", category: "Tech", country: "Global", industry: "Cybersecurity",
      shortDescription: "Funding for cybersecurity vendors and operators investing in defensive capability or product expansion.",
      fullDescription: "Supports cybersecurity product companies and operators investing in detection, response, or compliance certification capacity.",
      fundingMin: 20000, fundingMax: 200000, processingFee: 125, processingTime: "10–15 business days",
      eligibility: ["Operating cybersecurity business or qualifying enterprise buyer","Defensive capability plan"],
      documents: ["Business registration","Product or capability brief","Use-of-funds plan"],
      benefits: ["Technical reviewers","Certification cost coverage","Enterprise introductions"] },
    { id: "ai-research-grant", name: "Applied AI Research Grant", category: "Research", country: "Global", industry: "Artificial Intelligence",
      shortDescription: "Funding for applied AI teams shipping production systems with measurable business outcomes.",
      fullDescription: "Backs applied AI ventures shipping production systems — not pure research. Reviewers prioritize defensible data, working models, and a clear ROI path.",
      fundingMin: 25000, fundingMax: 260000, processingFee: 140, processingTime: "12–18 business days",
      eligibility: ["Operating AI company or research team with production ambitions","Working model or prototype"],
      documents: ["Incorporation document","Technical brief","Pipeline or pilot summary"],
      benefits: ["AI-specialist reviewers","Compute credit introductions","Follow-on capital network"] },
    { id: "real-estate-development", name: "Real Estate Development Grant", category: "Real Estate", country: "United States", industry: "Real Estate",
      shortDescription: "Predevelopment and gap capital for small developers in affordable housing or mixed-use projects.",
      fullDescription: "Funds predevelopment costs, design, and gap financing for small developers building affordable housing or mixed-use projects with documented community benefit.",
      fundingMin: 25000, fundingMax: 250000, processingFee: 145, processingTime: "12–18 business days",
      eligibility: ["Licensed developer or operating entity","Site control or letter of intent","Documented project plan"],
      documents: ["Entity registration","Site control documentation","Project pro forma"],
      benefits: ["Predevelopment-aware reviewers","Affordable housing tracks","Capital stack introductions"] },
    { id: "climate-resilience", name: "Climate Resilience Grant", category: "Sustainability", country: "Global", industry: "Climate & Resilience",
      shortDescription: "Funding for businesses building climate-resilience infrastructure, products, or services.",
      fullDescription: "Supports operators building or deploying climate-resilience capacity — water, flood, wildfire, heat resilience, or related insurance and data products.",
      fundingMin: 20000, fundingMax: 180000, processingFee: 115, processingTime: "12–18 business days",
      eligibility: ["Operating business with resilience product or service","Documented deployment plan"],
      documents: ["Business registration","Project plan","Deployment baseline"],
      benefits: ["Climate-specialist reviewers","Measurement & verification help","Insurance-sector introductions"] },
    { id: "youth-entrepreneur", name: "Youth Entrepreneur Grant", category: "Diversity", country: "Global", industry: "All Industries",
      shortDescription: "Early capital for entrepreneurs aged 18–30 building registered businesses with a clear plan.",
      fullDescription: "Backs young founders (18–30) with registered businesses moving from idea to first revenue. Mentor pairing is included.",
      fundingMin: 3000, fundingMax: 35000, processingFee: 45, processingTime: "5–10 business days",
      eligibility: ["Founder aged 18–30","Registered business","Documented business plan or MVP"],
      documents: ["Founder ID","Business registration","One-page plan"],
      benefits: ["Mentor pairing","Lower fee","Founder community access"] },
    { id: "second-chance-grant", name: "Second-Chance Business Grant", category: "Community", country: "United States", industry: "All Industries",
      shortDescription: "Funding for entrepreneurs with prior justice involvement building registered businesses.",
      fullDescription: "Supports formerly justice-involved entrepreneurs operating registered businesses, with documentation help and a dedicated reviewer pool.",
      fundingMin: 5000, fundingMax: 50000, processingFee: 50, processingTime: "7–14 business days",
      eligibility: ["Registered business owner","Documented business plan or operations"],
      documents: ["Owner ID","Business registration","Use-of-funds plan"],
      benefits: ["Dedicated reviewer pool","Documentation help","Mentor network access"] },
    { id: "disability-owned", name: "Disability-Owned Business Grant", category: "Diversity", country: "Global", industry: "All Industries",
      shortDescription: "Capital for businesses majority-owned by entrepreneurs with disabilities.",
      fullDescription: "Backs disability-owned businesses (51%+ ownership) operating with documented activity. Accessibility-focused investments receive priority.",
      fundingMin: 8000, fundingMax: 90000, processingFee: 65, processingTime: "7–14 business days",
      eligibility: ["51%+ disability-owned","Registered business in operation"],
      documents: ["Owner ID","Disability verification","Business registration"],
      benefits: ["Dedicated reviewer pool","Accessibility-investment tracks","Documentation help"] },
    { id: "lgbtq-business", name: "LGBTQ+ Business Grant", category: "Diversity", country: "Global", industry: "All Industries",
      shortDescription: "Capital for businesses majority-owned by LGBTQ+ entrepreneurs across qualifying industries.",
      fullDescription: "Supports LGBTQ+-owned ventures expanding revenue, headcount, or market reach. NGLCC certification accelerates review.",
      fundingMin: 8000, fundingMax: 95000, processingFee: 70, processingTime: "7–14 business days",
      eligibility: ["51%+ LGBTQ+ ownership","Registered business in operation"],
      documents: ["Owner ID","NGLCC certification (if available)","Business registration"],
      benefits: ["Dedicated reviewer pool","Certification support","Mentor network access"] },
    { id: "indigenous-business", name: "Indigenous Business Capital Grant", category: "Diversity", country: "Global", industry: "All Industries",
      shortDescription: "Funding for Indigenous-owned businesses and tribal enterprises building lasting community capacity.",
      fullDescription: "Backs Indigenous-owned ventures and tribal enterprises with documented activity. Community-benefit projects receive priority.",
      fundingMin: 10000, fundingMax: 130000, processingFee: 80, processingTime: "10–15 business days",
      eligibility: ["Indigenous ownership or tribal enterprise","Registered business or enterprise charter"],
      documents: ["Tribal enrollment or ownership verification","Business or enterprise registration","Use-of-funds plan"],
      benefits: ["Dedicated reviewer pool","Community-benefit tracks","Documentation help"] },
    { id: "creative-fashion", name: "Fashion & Apparel Grant", category: "Creative", country: "Global", industry: "Fashion & Apparel",
      shortDescription: "Funding for independent fashion labels and apparel makers scaling production or distribution.",
      fullDescription: "Backs independent labels scaling production runs, sustainable sourcing, or wholesale distribution. Sustainability documentation accelerates review.",
      fundingMin: 6000, fundingMax: 75000, processingFee: 60, processingTime: "7–14 business days",
      eligibility: ["Operating apparel brand with sales history","Production or sourcing plan"],
      documents: ["Business registration","Production cost summary","Sample lookbook"],
      benefits: ["Sustainability-focused tracks","Wholesale introductions","Documentation help"] },
    { id: "food-beverage-grant", name: "Food & Beverage Brand Grant", category: "Food", country: "Global", industry: "Food & Beverage",
      shortDescription: "Capital for CPG food and beverage brands scaling production, packaging, or retail distribution.",
      fullDescription: "Funds CPG food and beverage brands with shelf placement or DTC traction scaling production runs, packaging, or distribution.",
      fundingMin: 10000, fundingMax: 120000, processingFee: 85, processingTime: "7–14 business days",
      eligibility: ["Registered food or beverage brand","Active retail placement or DTC sales"],
      documents: ["Business registration","Sales summary","Production or co-packer quote"],
      benefits: ["Retail-aware reviewers","Co-packer introductions","Documentation help"] },
    { id: "professional-services", name: "Professional Services Grant", category: "Services", country: "Global", industry: "Professional Services",
      shortDescription: "Capital for consultancies, law, accounting, and agency businesses investing in capacity.",
      fullDescription: "Backs professional services firms — consultancies, agencies, law, accounting — investing in talent, systems, or new service lines.",
      fundingMin: 8000, fundingMax: 100000, processingFee: 75, processingTime: "5–10 business days",
      eligibility: ["Registered professional services firm","Active client base or contracts"],
      documents: ["Business registration","Most recent revenue summary","Hiring or systems plan"],
      benefits: ["Services-aware reviewers","Systems-investment tracks","Documentation help"] },
    { id: "franchise-expansion", name: "Franchise Expansion Grant", category: "SME", country: "United States", industry: "Franchise & Multi-Unit",
      shortDescription: "Capital for franchisees expanding to a second or third location with documented unit economics.",
      fullDescription: "Funds franchisees with at least one profitable unit expanding to additional locations. Franchisor approval and unit economics are reviewed.",
      fundingMin: 25000, fundingMax: 200000, processingFee: 120, processingTime: "10–15 business days",
      eligibility: ["At least one operating franchise unit","Franchisor approval for expansion"],
      documents: ["Franchise agreement","Unit P&L (12 months)","Site or LOI documentation"],
      benefits: ["Multi-unit reviewers","Site selection introductions","Documentation help"] },
    { id: "childcare-grant", name: "Childcare & Family Services Grant", category: "Community", country: "United States", industry: "Childcare & Family",
      shortDescription: "Funding for licensed childcare providers, family services, and early learning operators.",
      fullDescription: "Backs licensed childcare providers and family-services operators expanding capacity, staff, or facilities.",
      fundingMin: 8000, fundingMax: 90000, processingFee: 65, processingTime: "7–14 business days",
      eligibility: ["State-licensed childcare or family services provider","Documented enrollment"],
      documents: ["State license","Enrollment summary","Use-of-funds plan"],
      benefits: ["Licensing-aware reviewers","Facilities-investment tracks","Documentation help"] },
    { id: "sports-recreation", name: "Sports & Recreation Grant", category: "Community", country: "Global", industry: "Sports & Recreation",
      shortDescription: "Capital for gyms, sports clubs, and recreation operators investing in facilities or programs.",
      fullDescription: "Funds operating gyms, sports clubs, and recreation businesses investing in facilities, equipment, or community-access programs.",
      fundingMin: 8000, fundingMax: 100000, processingFee: 75, processingTime: "7–14 business days",
      eligibility: ["Operating sports or recreation business","Documented membership or program activity"],
      documents: ["Business registration","Membership or program summary","Facility plan"],
      benefits: ["Community-program tracks","Equipment financing introductions","Documentation help"] },
    { id: "tourism-grant", name: "Tourism & Cultural Grant", category: "Hospitality", country: "Global", industry: "Tourism & Culture",
      shortDescription: "Funding for tour operators, cultural venues, and destination businesses scaling capacity.",
      fullDescription: "Backs licensed tour operators, cultural venues, and destination businesses scaling programming, capacity, or international marketing.",
      fundingMin: 8000, fundingMax: 110000, processingFee: 80, processingTime: "10–15 business days",
      eligibility: ["Licensed tour, cultural, or destination operator","Documented bookings or programming"],
      documents: ["Operator license","Bookings or programming summary","Use-of-funds plan"],
      benefits: ["Seasonal-cycle aware","International marketing tracks","Documentation help"] },
    { id: "marine-fisheries", name: "Marine & Fisheries Grant", category: "Agriculture", country: "Global", industry: "Marine & Fisheries",
      shortDescription: "Funding for licensed fishers, aquaculture, and coastal businesses investing in sustainable capacity.",
      fullDescription: "Supports licensed fishing operators, aquaculture, and coastal processing businesses investing in sustainable capacity and certified sourcing.",
      fundingMin: 10000, fundingMax: 150000, processingFee: 95, processingTime: "12–18 business days",
      eligibility: ["Licensed marine or aquaculture operator","Sustainable capacity plan"],
      documents: ["Operator license","Vessel or facility documentation","Use-of-funds plan"],
      benefits: ["Sustainability-focused reviewers","Certification cost coverage","Equipment financing introductions"] },
    { id: "creative-gaming", name: "Gaming & Interactive Grant", category: "Creative", country: "Global", industry: "Gaming & Interactive",
      shortDescription: "Production funding for indie game studios and interactive media teams shipping titles.",
      fullDescription: "Backs indie game studios and interactive teams with a playable build and documented release plan. Distribution introductions are included.",
      fundingMin: 10000, fundingMax: 140000, processingFee: 95, processingTime: "10–15 business days",
      eligibility: ["Registered studio with playable build","Documented release plan"],
      documents: ["Studio registration","Playable build or trailer","Release plan"],
      benefits: ["Production-aware reviewers","Publisher introductions","Documentation help"] },
    { id: "music-industry", name: "Music Industry Grant", category: "Creative", country: "Global", industry: "Music",
      shortDescription: "Production and touring capital for independent artists and labels with documented audiences.",
      fullDescription: "Supports independent artists, labels, and music businesses with documented audience metrics investing in production, touring, or distribution.",
      fundingMin: 5000, fundingMax: 60000, processingFee: 55, processingTime: "7–14 business days",
      eligibility: ["Operating music business or artist entity","Documented audience or release history"],
      documents: ["Entity registration","Audience or streaming summary","Project budget"],
      benefits: ["Production-aware reviewers","Distribution introductions","Documentation help"] },
    { id: "publishing-grant", name: "Publishing & Media Grant", category: "Creative", country: "Global", industry: "Publishing & Journalism",
      shortDescription: "Capital for independent publishers, newsrooms, and journalism ventures investing in capacity.",
      fullDescription: "Backs independent publishers and newsrooms with documented audience investing in editorial capacity, distribution, or reader revenue infrastructure.",
      fundingMin: 8000, fundingMax: 90000, processingFee: 70, processingTime: "10–15 business days",
      eligibility: ["Registered publisher or newsroom","Documented audience or subscribers"],
      documents: ["Business registration","Audience / subscriber summary","Editorial plan"],
      benefits: ["Editorial-aware reviewers","Reader-revenue tracks","Documentation help"] },
    { id: "logistics-warehousing", name: "Warehousing & 3PL Grant", category: "Logistics", country: "United States", industry: "Warehousing & 3PL",
      shortDescription: "Capital for 3PL operators and warehousing businesses investing in racking, WMS, or labor.",
      fullDescription: "Funds 3PL operators and warehousing businesses investing in racking, WMS software, automation, or seasonal labor capacity.",
      fundingMin: 15000, fundingMax: 180000, processingFee: 110, processingTime: "10–15 business days",
      eligibility: ["Operating 3PL or warehousing business","Documented client base or capacity plan"],
      documents: ["Business registration","Client or capacity summary","Use-of-funds plan"],
      benefits: ["Operations-aware reviewers","Automation introductions","Documentation help"] },
    { id: "auto-repair-grant", name: "Auto Repair & Services Grant", category: "Trades", country: "United States", industry: "Auto Services",
      shortDescription: "Funding for licensed auto shops investing in lifts, diagnostics, or EV-service capability.",
      fullDescription: "Backs licensed auto repair, body, and service shops investing in equipment, diagnostics, or EV-service capability.",
      fundingMin: 8000, fundingMax: 90000, processingFee: 75, processingTime: "7–14 business days",
      eligibility: ["Licensed auto repair or service business","Insurance in good standing"],
      documents: ["Business license","Insurance certificate","Equipment quotes"],
      benefits: ["Trades-aware reviewers","EV-service tracks","Documentation help"] },
    { id: "beauty-wellness", name: "Beauty & Wellness Grant", category: "Services", country: "Global", industry: "Beauty & Wellness",
      shortDescription: "Capital for licensed salons, spas, and wellness operators expanding facilities or staff.",
      fullDescription: "Funds licensed salons, spas, and wellness operators investing in facility upgrades, staff expansion, or new service lines.",
      fundingMin: 6000, fundingMax: 75000, processingFee: 65, processingTime: "5–10 business days",
      eligibility: ["Licensed salon, spa, or wellness operator","Active client base"],
      documents: ["Business license","Revenue summary","Use-of-funds plan"],
      benefits: ["Services-aware reviewers","Facility-investment tracks","Documentation help"] },
    { id: "saas-growth", name: "SaaS Growth Grant", category: "Tech", country: "Global", industry: "Software (SaaS)",
      shortDescription: "Growth capital for SaaS businesses with documented MRR scaling sales, product, or infra.",
      fullDescription: "Backs SaaS businesses with documented MRR scaling sales capacity, product investment, or infrastructure. Unit-economics review is standard.",
      fundingMin: 20000, fundingMax: 220000, processingFee: 125, processingTime: "10–15 business days",
      eligibility: ["Operating SaaS company with documented MRR","Unit-economics plan"],
      documents: ["Incorporation document","MRR / cohort summary","Use-of-funds plan"],
      benefits: ["SaaS-specialist reviewers","Follow-on capital introductions","Documentation help"] },
    { id: "energy-efficiency", name: "Energy Efficiency Retrofit Grant", category: "Sustainability", country: "United States", industry: "Energy & Sustainability",
      shortDescription: "Funding for facility owners installing efficiency retrofits — HVAC, lighting, envelope, controls.",
      fullDescription: "Backs facility owners and operators installing measurable efficiency retrofits — HVAC, lighting, building envelope, and controls — with documented baseline.",
      fundingMin: 15000, fundingMax: 160000, processingFee: 100, processingTime: "10–15 business days",
      eligibility: ["Operating facility owner or long-term lessee","Documented energy baseline"],
      documents: ["Business registration","Utility baseline (12 months)","Retrofit scope of work"],
      benefits: ["Stackable with utility rebates","Measurement & verification help","Equipment financing introductions"] },
    { id: "social-enterprise", name: "Social Enterprise Grant", category: "Nonprofit", country: "Global", industry: "Social Enterprise",
      shortDescription: "Capital for revenue-generating social enterprises with documented community outcomes.",
      fullDescription: "Funds for-profit and hybrid social enterprises with revenue and documented community outcomes scaling programs or earned-revenue capacity.",
      fundingMin: 10000, fundingMax: 120000, processingFee: 80, processingTime: "10–15 business days",
      eligibility: ["Operating social enterprise with revenue","Documented impact outcomes"],
      documents: ["Entity registration","Most recent financials","Impact summary"],
      benefits: ["Impact-aware reviewers","Hybrid-capital introductions","Documentation help"] },
    { id: "research-commercialization", name: "Research Commercialization Grant", category: "Research", country: "United States", industry: "University Spinouts",
      shortDescription: "Translation capital for university spinouts moving research from lab to commercial pilot.",
      fullDescription: "Backs university spinouts and translational research ventures moving from lab to first commercial pilot. IP position and team are reviewed.",
      fundingMin: 25000, fundingMax: 250000, processingFee: 135, processingTime: "14–21 business days",
      eligibility: ["Incorporated spinout with IP position","Documented technology readiness level"],
      documents: ["Incorporation document","IP / license documentation","Commercialization plan"],
      benefits: ["Translation-aware reviewers","Pilot-customer introductions","Largest funding bands"] },
    { id: "pet-care-grant", name: "Pet Care & Veterinary Grant", category: "Services", country: "United States", industry: "Pet Care & Veterinary",
      shortDescription: "Capital for licensed veterinary clinics and pet-care businesses expanding facilities or staff.",
      fullDescription: "Funds licensed veterinary clinics, grooming, boarding, and pet-care operators investing in facilities, equipment, or staff capacity.",
      fundingMin: 8000, fundingMax: 95000, processingFee: 70, processingTime: "7–14 business days",
      eligibility: ["Licensed veterinary or pet-care business","Active client base"],
      documents: ["Business license","Revenue summary","Use-of-funds plan"],
      benefits: ["Services-aware reviewers","Equipment financing introductions","Documentation help"] },
    { id: "water-infrastructure", name: "Water Infrastructure Grant", category: "Sustainability", country: "Global", industry: "Water & Infrastructure",
      shortDescription: "Funding for businesses deploying water treatment, conservation, or distribution infrastructure.",
      fullDescription: "Backs operators deploying water treatment, conservation, irrigation efficiency, or distribution infrastructure with documented community or commercial benefit.",
      fundingMin: 20000, fundingMax: 200000, processingFee: 120, processingTime: "12–18 business days",
      eligibility: ["Operating business with water infrastructure project","Documented deployment plan"],
      documents: ["Business registration","Project plan","Supplier quote"],
      benefits: ["Infrastructure-aware reviewers","Stackable with municipal incentives","Measurement & verification help"] }
  ];

  window.CB = {
    fmt: function (n) {
      return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
    },
    getGrant: function (id) {
      return window.CB_GRANTS.find(function (g) { return g.id === id; });
    },
    qs: function (k) {
      return new URLSearchParams(window.location.search).get(k);
    },
    toast: function (msg) {
      var t = document.createElement("div");
      t.textContent = msg;
      t.style.cssText = "position:fixed;top:20px;left:50%;transform:translateX(-50%);background:#0F172A;color:#fff;padding:10px 16px;border-radius:8px;font-size:13px;z-index:100;box-shadow:0 8px 24px rgba(0,0,0,.2);";
      document.body.appendChild(t);
      setTimeout(function () { t.style.transition = "opacity .3s"; t.style.opacity = "0"; }, 1800);
      setTimeout(function () { t.remove(); }, 2300);
    },
    copy: function (text, btn) {
      navigator.clipboard.writeText(text).then(function () {
        if (btn) {
          var prev = btn.textContent;
          btn.textContent = "Copied";
          setTimeout(function () { btn.textContent = prev; }, 1400);
        } else {
          window.CB.toast("Copied to clipboard");
        }
      });
    }
  };

  // Mark active nav link
  document.addEventListener("DOMContentLoaded", function () {
    var path = window.location.pathname.split("/").pop() || "home.html";
    document.querySelectorAll(".nav a").forEach(function (a) {
      var href = a.getAttribute("href");
      if (href === path) a.classList.add("active");
    });
  });
})();
